### ISSUE TITLE
[SP 3.0] [Create by yourself] Refactor product creation from the constructor

### ISSUE THREAD

**Issue by Pipuss** [ita-social-projects/horondi_client_fe#2003]
Please, go to Create by yourself page on client side. 
Make sure that constructor works as expected according to all of functionality below. 

___________________________________________________________

![image](https://user-images.githubusercontent.com/45914032/174303346-544f6147-9ff1-4423-92ec-1b2c6b3ef0eb.png)
___________________________________________________________

`The list of tasks to close this issue:`
- [x] ita-social-projects/horondi_client_fe#2010
- [x] ita-social-projects/horondi_client_fe#2012
- [x] ita-social-projects/horondi_client_fe#2013
- [x] ita-social-projects/horondi_admin#1388
- [x] ita-social-projects/horondi_client_be#1218
- [x] ita-social-projects/horondi_admin#1475
- [x] ita-social-projects/horondi_client_be#1298
- [x] ita-social-projects/horondi_admin#1430
- [x] ita-social-projects/horondi_admin#1431
- [x] ita-social-projects/horondi_client_be#1249
- [x] ita-social-projects/horondi_admin#1461
- [x] #2212
- [x] ita-social-projects/horondi_client_fe#2195
- [x] ita-social-projects/horondi_admin#1465
- [x] ita-social-projects/horondi_client_fe#2164
- [x] ita-social-projects/horondi_client_fe#2152
